# action.yml
name: 'Scenario test action'
description: 'scenario test action for ROS packages'
inputs:
  base-image:
    description: 'name of base image'
    required: false
    default: ros
  tag:
    description: 'name of tag'
    required: false
    default: 'foxy'
  rosdistro:
    description: 'name of rosdistro'
    required: false
    default: 'foxy'
  repos_url:
    description: 'url of repos file you want to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base-image }}
    - ${{ inputs.tag }}
    - ${{ inputs.rosdistro }}
    - ${{ inputs.repos_url }}