name: test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: A test job for ros integration test action
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [foxy, galactic]
        repository_type: [public, private]
    steps:
    # To use this repository's private action, you must check out the repository
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: repos_${{ matrix.rosdistro }}_${{ matrix.repository_type }}
        path: .github/workflows/${{ matrix.repository_type }}.repos
    - name: Run ros integration test action
      uses: ./
      with:
        base_image: ros
        tag: ${{ matrix.rosdistro }}
        rosdistro: ${{ matrix.rosdistro }}
        test_command: ls /colcon_ws/src
        check_result_command: ls /colcon_ws/src
        artifact_name: artifacts_${{ matrix.rosdistro }}_${{ matrix.repository_type }}
        repos_artifact_name: repos_${{ matrix.rosdistro }}_${{ matrix.repository_type }}
        repos_filename: ${{ matrix.repository_type }}.repos
        build_args: --symlink-install
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        ACTIONS_RUNTIME_URL: ${{ env.ACTIONS_RUNTIME_URL }}
        GITHUB_RUN_ID: ${env.GITHUB_RUN_ID}
        GITHUB_CLONE_TOKEN: ${{ secrets.WAMV_TAN_BOT_SECRET }} 